// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6m2PUzlt3bHmhalMzpfRFPoQjey9CQ6U',
    appId: '1:769618803055:web:767ab7c6aa513bbfd7109a',
    messagingSenderId: '769618803055',
    projectId: 'tester-ae1f5',
    authDomain: 'tester-ae1f5.firebaseapp.com',
    storageBucket: 'tester-ae1f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdFJ2t8EEa-47REUNjAMCtVGt5KHzwR5w',
    appId: '1:769618803055:android:5a57b9d81a1b4334d7109a',
    messagingSenderId: '769618803055',
    projectId: 'tester-ae1f5',
    storageBucket: 'tester-ae1f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpuiCkLMHmJTiVCdytkHMNCb5oxirIPvk',
    appId: '1:769618803055:ios:5cf5c8ab1fee0214d7109a',
    messagingSenderId: '769618803055',
    projectId: 'tester-ae1f5',
    storageBucket: 'tester-ae1f5.appspot.com',
    androidClientId: '769618803055-4tu4iv29svbrnr94935i6671n0sr3mcr.apps.googleusercontent.com',
    iosClientId: '769618803055-dpei88ja14ve2frjf4e3lmgkqq439ta6.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpuiCkLMHmJTiVCdytkHMNCb5oxirIPvk',
    appId: '1:769618803055:ios:0c8af7e39e28c5bad7109a',
    messagingSenderId: '769618803055',
    projectId: 'tester-ae1f5',
    storageBucket: 'tester-ae1f5.appspot.com',
    androidClientId: '769618803055-4tu4iv29svbrnr94935i6671n0sr3mcr.apps.googleusercontent.com',
    iosClientId: '769618803055-i1l05oi04u691ve06sgd2ifsegbgonos.apps.googleusercontent.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
